# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sniper Tech
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/ga_blog" # the subpath of the site
url: "https://albert97.github.io" # the base hostname & protocol for the site
og_image: /assets/img/Malta.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog
    - name: Code

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: albertzhang378@gmailcom
      link: mailto:yourmail@domain.com
    - name: WeChat
      value: YourWeChatUsername
      link: "#"
  follow:
    - name: Twitter
      link: https://twitter.com
      username: "@YourTwitterUsername"
    - name: Facebook
      link: https://www.facebook.com
    - name: LinkedIn
      link: https://www.linkedin.com/in/albert-ziqi-zhang-a1626341
    - name: GitHub
      link: http://github.com/YourGitHubUsername
    - name: Weibo
      link: http://weibo.com/u/YourWeiboUsername
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
      
# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
